language: android
#jdk:
#  - oraclejdk7
sudo: required
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-22
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - '.+'
before_install:
    # Gradle
    - wget -q http://services.gradle.org/distributions/gradle-4.1-all.zip
    - unzip -q gradle-4.1-all.zip
    - export GRADLE_HOME=$PWD/gradle-4.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    # Get Android NDK
#    - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
#    - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - rm -fr $HOME/android-ndk-r16b
  - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  - unzip -oq android-ndk-r16b-linux-x86_64.zip
  - rm android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r16b
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &