language: android
jdk: oraclejdk8
sudo: true
os:
  - linux
addons:
  apt_packages:
    - pandoc
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-22
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
    - add-on
    - extra
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - '.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
# Gradle
  - wget -q http://services.gradle.org/distributions/gradle-4.1-all.zip
  - unzip -q gradle-4.1-all.zip
  - export GRADLE_HOME=$PWD/gradle-4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &